### ISSUE TITLE
Change a widget's color by using a color list - not work?

### ISSUE THREAD

**Issue by Qlinkwisp** [johannesegger/VuforiaStudioExtensions#1]
I think parameter for setColor and parameter from list changeColor is not match

scope.setColor = (widgetId, r, g, b)

and 

following your example
changeColor parameter for setColor is looklike

scope.setColor("model", colors[selectedColor])

Im not good in java but following instruction is not work for me 
but after i try to change parameter type Its work

Thank you

**Comment by johannesegger** [comment]
Thanks for reporting this. I updated the sample.

**Comment by Qlinkwisp** [comment]
> Thanks for reporting this. I updated the sample.

Thank you
