### ISSUE TITLE
want 1 lap rotation after click

### ISSUE THREAD

**Issue by Qlinkwisp** [johannesegger/VuforiaStudioExtensions#2]
i find the way to rotate model just 1 lap after click

any suggestion?

**Comment by johannesegger** [comment]
That is more difficult than it should be. There should be a function that modifies a property for a specific time.

**Comment by johannesegger** [comment]
It's now built into `animateBy`. You can do for example `animateBy("model", "rx", 10, 50, 36)` which modifies property "rx" every 50 ms by 10 degrees for 36 times.

Note that you have to add [the latest version of fn.js](https://raw.githubusercontent.com/johannesegger/VuforiaStudioExtensions/master/fn.js) again to your project.

**Comment by Qlinkwisp** [comment]
> It's now built into `animateBy`. You can do for example `animateBy("model", "rx", 10, 50, 36)` which modifies property "rx" every 50 ms by 10 degrees for 36 times.
> 
> Note that you have to add [the latest version of fn.js](https://raw.githubusercontent.com/johannesegger/VuforiaStudioExtensions/master/fn.js) again to your project.

thank you
