### ISSUE TITLE
Await an animation to complete

### ISSUE THREAD

**Issue by smallrobots** [johannesegger/VuforiaStudioExtensions#4]
Hello, 

Great library! :-)
Question: I understand that I can issue several animations on the same model and get all the animations perform at the same time (provided that they animate different properties). What about if I want to animate a sequence, how do I "await" for an animation to complete?

Many thanks!

**Comment by johannesegger** [comment]
Starting an animation returns a `Promise` which you can either `await` or provide a continuation function.

* `await` (not sure if every device supports [async/await](https://caniuse.com/mdn-javascript_operators_await))
  ```js
  $scope.runAnimation = async () =>
  {
      await $scope.fadeOut("model")
      console.log("Fading out done.")
  }
  ```
* Continuation function (this should work everywhere but is not so nice to use):
  ```js
  $scope.runAnimation = () =>
  {
      $scope.fadeOut("model").then(() => console.log("Fading out done."))
  }
  ```

**Comment by smallrobots** [comment]
I've tried first approach and it looks "promising" :-)
Many thanks!
